var resultsList2024 = [
  {
    key: "0_0", //asparagus
    anabat: "Rfer",
    name: "Greater Horseshoe",
    count: 1, //divide by days
  },
  {
    key: "0_1",
    anabat: "Rhip",
    name: "LHB",
    count: 1,
  },
  {
    key: "0_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 70,
  },
  {
    key: "0_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 470, ///?
  },
  {
    key: "0_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 4,
  },
  {
    key: "0_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 7,
  },
  {
    key: "0_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 19,
  },
  {
    key: "0_7",
    anabat: "Plaur",
    name: "Long-eared",
    count: 0,
  },
  {
    key: "0_8",
    anabat: " ",
    name: "Bechsteins",
    count: 0,
  },
  {
    key: "0_9",
    anabat: "Bbarb",
    name: "Barbesterelle",
    count: 11,
  },
  {
    key: "1_0", //barton town
    anabat: "Rfer",
    name: "GHB",
    count: 11,
  },
  {
    key: "1_1",
    anabat: "Rhip",
    name: "LHB",
    count: 1,
  },
  {
    key: "1_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 153,
  },
  {
    key: "1_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 37,
  },
  {
    key: "1_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 38,
  },
  {
    key: "1_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 85,
  },
  {
    key: "1_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 16,
  },
  {
    key: "1_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 0,
  },
  {
    key: "1_8",
    anabat: " ",
    name: "Bechsteins",
    count: 0,
  },
  {
    key: "1_9",
    anabat: "Bbarb",
    name: "barbestrelle",
    count: 3,
  },
  {
    key: "2_0", //Big + Bumpston******************************//NOT READY/////
    anabat: "Rfer",
    name: "GHB",
    count: 33,
  },
  {
    key: "2_1",
    anabat: "Rhip",
    name: "LHB",
    count: 2,
  },
  {
    key: "2_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 282,
  },
  {
    key: "2_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 312,
  },
  {
    key: "2_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 15,
  },
  {
    key: "2_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 27,
  },
  {
    key: "2_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 55,
  },
  {
    key: "2_7",
    anabat: "Plaur",
    name: "Long eared",
    count: 1,
  },
  {
    key: "2_8",
    anabat: " ",
    name: "Bechsteins",
    count: 0,
  },
  {
    key: "2_9",
    anabat: "Bbarb",
    name: "Long eared",
    count: 6,
  },
  {
    key: "3_0", //FIELD KITCHEN******************************////
    anabat: "Rfer",
    name: "GHB",
    count: 4,
  },
  {
    key: "3_1",
    anabat: "Rhip",
    name: "LHB",
    count: 1,
  },
  {
    key: "3_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 13,
  },
  {
    key: "3_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 4,
  },
  {
    key: "3_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 0,
  },
  {
    key: "3_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 1, //?
  },
  {
    key: "3_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 7,
  },
  {
    key: "3_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 0,
  },
  {
    key: "3_8",
    anabat: " ",
    name: "Bechstein's",
    count: 0,
  },
  {
    key: "3_9",
    anabat: "Bbarb",
    name: "barbestrelle",
    count: 0,
  },
  {
    key: "4_0", //Guys Field*****************************///
    anabat: "Rfer",
    name: "GHB",
    count: 6,
  },
  {
    key: "4_1",
    anabat: "Rhip",
    name: "LHB",
    count: 1,
  },
  {
    key: "4_2",
    anabat: "Ppip",
    name: "Common Pipestrelle",
    count: 29,
  },
  {
    key: "4_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 142,
  },
  {
    key: "4_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 1,
  },
  {
    key: "4_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 2, // whiskered or Brant
  },
  {
    key: "4_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 15,
  },
  {
    key: "4_7",
    anabat: "Plaur",
    name: "Long-eared",
    count: 1,
  },
  {
    key: "4_8",
    anabat: " ",
    name: "Bechstein's",
    count: 0,
  },
  {
    key: "4_9",
    anabat: "Bbarb",
    name: "barb",
    count: 3,
  },
  {
    key: "5_0", //JOHN SMITH*********************////
    anabat: "Rfer",
    name: "GHB",
    count: 5,
  },
  {
    key: "5_1",
    anabat: "Rhip",
    name: "LHB",
    count: 3,
  },
  {
    key: "5_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 280,
  },
  {
    key: "5_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 10,
  },
  {
    key: "5_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 3,
  },
  {
    key: "5_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 3,
  },
  {
    key: "5_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 11,
  },
  {
    key: "5_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 2,
  },
  {
    key: "5_8",
    anabat: " ",
    name: "Bechstein's",
    count: 0,
  },
  {
    key: "5_9",
    anabat: "Bbarb",
    name: "bbarb",
    count: 2,
  },
  {
    key: "6_0", //POLYTUNNELS - NOT FINISHED//***************************** */
    anabat: "Rfer",
    name: "GHB",
    count: 6,
  },
  {
    key: "6_1",
    anabat: "Rhip",
    name: "LHB",
    count: 7,
  },
  {
    key: "6_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 7,
  },
  {
    key: "6_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 1,
  },
  {
    key: "6_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 6,
  },
  {
    key: "6_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 10,
  },
  {
    key: "6_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 4,
  },
  {
    key: "6_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 2,
  },
  {
    key: "6_8",
    anabat: " ",
    name: "Bechstein's",
    count: 5,
  },
  {
    key: "6_9",
    anabat: "Bbarb",
    name: "bbarb",
    count: 2,
  },
  {
    key: "7_0", //TUCKERS FIELDS//************NOT FINISHED************* */
    anabat: "Rfer",
    name: "GHB",
    count: 2,
  },
  {
    key: "7_1",
    anabat: "Rhip",
    name: "LHB",
    count: 2,
  },
  {
    key: "7_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 2,
  },
  {
    key: "7_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 5,
  },
  {
    key: "7_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 9,
  },
  {
    key: "7_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 10,
  },
  {
    key: "7_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 5,
  },
  {
    key: "7_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 8,
  },
  {
    key: "7_8",
    anabat: " ",
    name: "Bechstein's",
    count: 12,
  },
  {
    key: "7_9",
    anabat: "Bbarb",
    name: "bbarb",
    count: 8,
  },
  {
    key: "8_0", //TWO RESERVOIRS//////************************* */
    anabat: "Rfer",
    name: "GHB",
    count: 59,
  },
  {
    key: "8_1",
    anabat: "Rhip",
    name: "LHB",
    count: 0,
  },
  {
    key: "8_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 143,
  },
  {
    key: "8_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 150,
  },
  {
    key: "8_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 0,
  },
  {
    key: "8_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 1,
  },
  {
    key: "8_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 38,
  },
  {
    key: "8_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 0,
  },
  {
    key: "8_8",
    anabat: " ",
    name: "Bechstein's",
    count: 0,
  },
  {
    key: "8_9",
    anabat: "Bbarb",
    name: "bBarb",
    count: 2,
  },
  {
    key: "9_0", //GLORIAS WOOD
    anabat: "Rfer",
    name: "GHB",
    count: 13,
  },
  {
    key: "9_1",
    anabat: "Rhip",
    name: "LHB",
    count: 1,
  },
  {
    key: "9_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 20,
  },
  {
    key: "9_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 3,
  },
  {
    key: "9_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 0,
  },
  {
    key: "9_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 0,
  },
  {
    key: "9_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 7,
  },
  {
    key: "9_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 0,
  },
  {
    key: "9_8",
    anabat: " ",
    name: "Bechstein's",
    count: 0,
  },
  {
    key: "9_9",
    anabat: "Bbarb",
    name: "bBarb",
    count: 0,
  },
  {
    key: "10_0", //BLANK//////////////////////////////
    anabat: "Rfer",
    name: "GHB",
    count: 0,
  },
  {
    key: "10_1",
    anabat: "Rhip",
    name: "LHB",
    count: 0,
  },
  {
    key: "10_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 0,
  },
  {
    key: "10_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 0,
  },
  {
    key: "10_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 0,
  },
  {
    key: "10_5",
    anabat: "MbraMmys",
    name: "Myotis Brandt's / Whiskered",
    count: 0,
  },
  {
    key: "10_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 0,
  },
  {
    key: "10_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 0,
  },
  {
    key: "10_8",
    anabat: " ",
    name: "Bechstein's",
    count: 0,
  },
  {
    key: "10_9",
    anabat: "Bbarb",
    name: "Barbastelle",
    count: 0,
  },
];
