var resultsList2024 = [
  {
    key: "0_0", //elderflower
    anabat: "Rfer",
    name: "Greater Horseshoe",
    count: 2, //divide by days
  },
  {
    key: "0_1",
    anabat: "Rhip",
    name: "LHB",
    count: 10,
  },
  {
    key: "0_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 8,
  },
  {
    key: "0_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 1,
  },
  {
    key: "0_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 3,
  },
  {
    key: "0_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 3,
  },
  {
    key: "0_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 8,
  },
  {
    key: "0_7",
    anabat: "Plaur",
    name: "Long-eared",
    count: 5,
  },
  {
    key: "0_8",
    anabat: " ",
    name: "Bechsteins",
    count: 1,
  },
  {
    key: "0_9",
    anabat: "Bbarb",
    name: "Barbesterelle",
    count: 11,
  },
  {
    key: "1_0", //watersports
    anabat: "Rfer",
    name: "GHB",
    count: 5,
  },
  {
    key: "1_1",
    anabat: "Rhip",
    name: "LHB",
    count: 8,
  },
  {
    key: "1_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 10,
  },
  {
    key: "1_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 9,
  },
  {
    key: "1_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 3,
  },
  {
    key: "1_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 5,
  },
  {
    key: "1_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 5,
  },
  {
    key: "1_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 7,
  },
  {
    key: "1_8",
    anabat: " ",
    name: "Bechsteins",
    count: 3,
  },
  {
    key: "1_9",
    anabat: "Bbarb",
    name: "barbestrelle",
    count: 2,
  },
  {
    key: "2_0", //nBarkington pathfield
    anabat: "Rfer",
    name: "GHB",
    count: 8,
  },
  {
    key: "2_1",
    anabat: "Rhip",
    name: "LHB",
    count: 6,
  },
  {
    key: "2_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 2,
  },
  {
    key: "2_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 8,
  },
  {
    key: "2_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 4,
  },
  {
    key: "2_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 8,
  },
  {
    key: "2_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 9,
  },
  {
    key: "2_7",
    anabat: "Plaur",
    name: "Long eared",
    count: 6,
  },
  {
    key: "2_8",
    anabat: " ",
    name: "Bechsteins",
    count: 2,
  },
  {
    key: "2_9",
    anabat: "Bbarb",
    name: "Long eared",
    count: 8,
  },
  {
    key: "3_0", //tuckers bottom
    anabat: "Rfer",
    name: "GHB",
    count: 5,
  },
  {
    key: "3_1",
    anabat: "Rhip",
    name: "LHB",
    count: 1,
  },
  {
    key: "3_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 2,
  },
  {
    key: "3_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 9,
  },
  {
    key: "3_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 6,
  },
  {
    key: "3_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 2,
  },
  {
    key: "3_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 6,
  },
  {
    key: "3_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 8,
  },
  {
    key: "3_8",
    anabat: " ",
    name: "Bechstein's",
    count: 4,
  },
  {
    key: "3_9",
    anabat: "Bbarb",
    name: "barbestrelle",
    count: 8,
  },
  {
    key: "4_0", //new hedge dipway
    anabat: "Rfer",
    name: "GHB",
    count: 7,
  },
  {
    key: "4_1",
    anabat: "Rhip",
    name: "LHB",
    count: 9,
  },
  {
    key: "4_2",
    anabat: "Ppip",
    name: "Common Pipestrelle",
    count: 4,
  },
  {
    key: "4_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 0,
  },
  {
    key: "4_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 3,
  },
  {
    key: "4_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 5,
  },
  {
    key: "4_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 8,
  },
  {
    key: "4_7",
    anabat: "Plaur",
    name: "Long-eared",
    count: 8,
  },
  {
    key: "4_8",
    anabat: " ",
    name: "Bechstein's",
    count: 10,
  },
  {
    key: "4_9",
    anabat: "Bbarb",
    name: "barb",
    count: 2,
  },
  {
    key: "5_0", //yarbury reservoir
    anabat: "Rfer",
    name: "GHB",
    count: 4,
  },
  {
    key: "5_1",
    anabat: "Rhip",
    name: "LHB",
    count: 8,
  },
  {
    key: "5_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 3,
  },
  {
    key: "5_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 6,
  },
  {
    key: "5_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 1,
  },
  {
    key: "5_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 5,
  },
  {
    key: "5_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 5,
  },
  {
    key: "5_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 2,
  },
  {
    key: "5_8",
    anabat: " ",
    name: "Bechstein's",
    count: 0,
  },
  {
    key: "5_9",
    anabat: "Bbarb",
    name: "bbarb",
    count: 2,
  },
  {
    key: "6_0", //glorias ford
    anabat: "Rfer",
    name: "GHB",
    count: 6,
  },
  {
    key: "6_1",
    anabat: "Rhip",
    name: "LHB",
    count: 7,
  },
  {
    key: "6_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 7,
  },
  {
    key: "6_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 1,
  },
  {
    key: "6_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 6,
  },
  {
    key: "6_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 10,
  },
  {
    key: "6_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 4,
  },
  {
    key: "6_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 2,
  },
  {
    key: "6_8",
    anabat: " ",
    name: "Bechstein's",
    count: 5,
  },
  {
    key: "6_9",
    anabat: "Bbarb",
    name: "bbarb",
    count: 2,
  },
  {
    key: "7_0", //greeen lane
    anabat: "Rfer",
    name: "GHB",
    count: 2,
  },
  {
    key: "7_1",
    anabat: "Rhip",
    name: "LHB",
    count: 2,
  },
  {
    key: "7_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 2,
  },
  {
    key: "7_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 5,
  },
  {
    key: "7_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 9,
  },
  {
    key: "7_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 10,
  },
  {
    key: "7_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 5,
  },
  {
    key: "7_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 8,
  },
  {
    key: "7_8",
    anabat: " ",
    name: "Bechstein's",
    count: 12,
  },
  {
    key: "7_9",
    anabat: "Bbarb",
    name: "bbarb",
    count: 8,
  },
  {
    key: "8_0", //broad stannings
    anabat: "Rfer",
    name: "GHB",
    count: 6,
  },
  {
    key: "8_1",
    anabat: "Rhip",
    name: "LHB",
    count: 8,
  },
  {
    key: "8_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 9,
  },
  {
    key: "8_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 3,
  },
  {
    key: "8_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 3,
  },
  {
    key: "8_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 8,
  },
  {
    key: "8_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 9,
  },
  {
    key: "8_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 2,
  },
  {
    key: "8_8",
    anabat: " ",
    name: "Bechstein's",
    count: 8,
  },
  {
    key: "8_9",
    anabat: "Bbarb",
    name: "bBarb",
    count: 11,
  },
  {
    key: "9_0", //top hedge - big field
    anabat: "Rfer",
    name: "GHB",
    count: 7,
  },
  {
    key: "9_1",
    anabat: "Rhip",
    name: "LHB",
    count: 8,
  },
  {
    key: "9_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 9,
  },
  {
    key: "9_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 4,
  },
  {
    key: "9_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 2,
  },
  {
    key: "9_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 8,
  },
  {
    key: "9_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 9,
  },
  {
    key: "9_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 6,
  },
  {
    key: "9_8",
    anabat: " ",
    name: "Bechstein's",
    count: 4,
  },
  {
    key: "9_9",
    anabat: "Bbarb",
    name: "bBarb",
    count: 7,
  },
  {
    key: "10_0", //short hedges Bakers park
    anabat: "Rfer",
    name: "GHB",
    count: 8,
  },
  {
    key: "10_1",
    anabat: "Rhip",
    name: "LHB",
    count: 2,
  },
  {
    key: "10_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 3,
  },
  {
    key: "10_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 2,
  },
  {
    key: "10_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 8,
  },
  {
    key: "10_5",
    anabat: "MbraMmys",
    name: "Myotis Brandt's / Whiskered",
    count: 9,
  },
  {
    key: "10_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 9,
  },
  {
    key: "10_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 5,
  },
  {
    key: "10_8",
    anabat: " ",
    name: "Bechstein's",
    count: 4,
  },
  {
    key: "10_9",
    anabat: "Bbarb",
    name: "Barbastelle",
    count: 3,
  },
];
