var resultsList2023 = [
  {
    key: "0_0",
    anabat: "Rfer",
    name: "GHB",
    count: 2, //divide by days
  },
  {
    key: "0_1",
    anabat: "Rhip",
    name: "LHB",
    count: 0,
  },
  {
    key: "0_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 9,
  },
  {
    key: "0_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 75,
  },
  {
    key: "0_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 0,
  },
  {
    key: "0_5",
    anabat: "MbraMmys",
    name: "Myotis Brandt's / Whiskered",
    count: 0,
  },
  {
    key: "0_6",
    anabat: "Mnat",
    name: "Natterers",
    count: 0,
  },
  {
    key: "0_7",
    anabat: "NSL",
    name: "Nyctalus: Leislers, Noctule",
    count: 2,
  },
  {
    key: "0_8",
    anabat: "Plaur",
    name: "Long eared",
    count: 0,
  },
  {
    key: "0_9",
    anabat: "Bbarb",
    name: "Long eared",
    count: 0,
  },
  {
    key: "1_0", //next
    anabat: "Rfer",
    name: "GHB",
    count: 1,
  },
  {
    key: "1_1",
    anabat: "Rhip",
    name: "LHB",
    count: 0,
  },
  {
    key: "1_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 24,
  },
  {
    key: "1_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 9,
  },
  {
    key: "1_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 23,
  },
  {
    key: "1_5",
    anabat: "MbraMmys",
    name: "Myotis Brandt's / Whiskered",
    count: 28,
  },
  {
    key: "1_6",
    anabat: "Mnat",
    name: "Natterers",
    count: 0,
  },
  {
    key: "1_7",
    anabat: "NSL",
    name: "Nyctalus: Leislers, Noctule",
    count: 1,
  },
  {
    key: "1_8",
    anabat: "Plaur",
    name: "Long eared",
    count: 0,
  },
  {
    key: "1_9",
    anabat: "Bbarb",
    name: "Long eared",
    count: 0,
  },
  {
    key: "2_0", //next
    anabat: "Rfer",
    name: "GHB",
    count: 0.2,
  },
  {
    key: "2_1",
    anabat: "Rhip",
    name: "LHB",
    count: 0,
  },
  {
    key: "2_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 11,
  },
  {
    key: "2_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 39.4,
  },
  {
    key: "2_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 0,
  },
  {
    key: "2_5",
    anabat: "MbraMmys",
    name: "Myotis Brandt's / Whiskered",
    count: 0.4,
  },
  {
    key: "2_6",
    anabat: "Mnat",
    name: "Natterers",
    count: 0.2,
  },
  {
    key: "2_7",
    anabat: "NSL",
    name: "Nyctalus: Leislers, Noctule",
    count: 0.2,
  },
  {
    key: "2_8",
    anabat: "Plaur",
    name: "Long eared",
    count: 0,
  },
  {
    key: "2_9",
    anabat: "Bbarb",
    name: "Long eared",
    count: 0,
  },
  {
    key: "3_0", //next
    anabat: "Rfer",
    name: "GHB",
    count: 0.1,
  },
  {
    key: "3_1",
    anabat: "Rhip",
    name: "LHB",
    count: 0,
  },
  {
    key: "3_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 23.9,
  },
  {
    key: "3_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 27.3,
  },
  {
    key: "3_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 0,
  },
  {
    key: "3_5",
    anabat: "MbraMmys",
    name: "Myotis Brandt's / Whiskered",
    count: 0,
  },
  {
    key: "3_6",
    anabat: "Mnat",
    name: "Natterers",
    count: 0,
  },
  {
    key: "3_7",
    anabat: "NSL",
    name: "Nyctalus: Leislers, Noctule",
    count: 0.3,
  },
  {
    key: "3_8",
    anabat: "Plaur",
    name: "Long eared",
    count: 0,
  },
  {
    key: "3_9",
    anabat: "Bbarb",
    name: "Long eared",
    count: 0,
  },
  {
    key: "4_0", //next
    anabat: "Rfer",
    name: "GHB",
    count: 0.9,
  },
  {
    key: "4_1",
    anabat: "Rhip",
    name: "LHB",
    count: 0,
  },
  {
    key: "4_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 51.6,
  },
  {
    key: "4_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 6.1,
  },
  {
    key: "4_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 2.9,
  },
  {
    key: "4_5",
    anabat: "MbraMmys",
    name: "Myotis Brandt's / Whiskered",
    count: 4.3,
  },
  {
    key: "4_6",
    anabat: "Mnat",
    name: "Natterers",
    count: 0.3,
  },
  {
    key: "4_7",
    anabat: "NSL",
    name: "Nyctalus: Leislers, Noctule",
    count: 0.4,
  },
  {
    key: "4_8",
    anabat: "Plaur",
    name: "Long eared",
    count: 0,
  },
  {
    key: "4_9",
    anabat: "Bbarb",
    name: "Long eared",
    count: 0,
  },
  {
    key: "5_0", //next
    anabat: "Rfer",
    name: "GHB",
    count: 1,
  },
  {
    key: "5_1",
    anabat: "Rhip",
    name: "LHB",
    count: 0.2,
  },
  {
    key: "5_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 19.6,
  },
  {
    key: "5_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 45,
  },
  {
    key: "5_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 0.8,
  },
  {
    key: "5_5",
    anabat: "MbraMmys",
    name: "Myotis Brandt's / Whiskered",
    count: 0.2,
  },
  {
    key: "5_6",
    anabat: "Mnat",
    name: "Natterers",
    count: 0,
  },
  {
    key: "5_7",
    anabat: "NSL",
    name: "Nyctalus: Leislers, Noctule",
    count: 1.2,
  },
  {
    key: "5_8",
    anabat: "Plaur",
    name: "Long eared",
    count: 0,
  },
  {
    key: "5_9",
    anabat: "Bbarb",
    name: "Long eared",
    count: 0,
  },
  {
    key: "6_0", //next
    anabat: "Rfer",
    name: "GHB",
    count: 0.4,
  },
  {
    key: "6_1",
    anabat: "Rhip",
    name: "LHB",
    count: 0,
  },
  {
    key: "6_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 7,
  },
  {
    key: "6_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 30.1,
  },
  {
    key: "6_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 2.1,
  },
  {
    key: "6_5",
    anabat: "MbraMmys",
    name: "Myotis Brandt's / Whiskered",
    count: 4.3,
  },
  {
    key: "6_6",
    anabat: "Mnat",
    name: "Natterers",
    count: 0,
  },
  {
    key: "6_7",
    anabat: "NSL",
    name: "Nyctalus: Leislers, Noctule",
    count: 0.1,
  },
  {
    key: "6_8",
    anabat: "Plaur",
    name: "Long eared",
    count: 0,
  },
  {
    key: "6_9",
    anabat: "Bbarb",
    name: "Long eared",
    count: 0,
  },
  {
    key: "7_0", //next
    anabat: "Rfer",
    name: "GHB",
    count: 17.6,
  },
  {
    key: "7_1",
    anabat: "Rhip",
    name: "LHB",
    count: 0,
  },
  {
    key: "7_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 8,
  },
  {
    key: "7_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 68.6,
  },
  {
    key: "7_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 52.8,
  },
  {
    key: "7_5",
    anabat: "MbraMmys",
    name: "Myotis Brandt's / Whiskered",
    count: 52.6,
  },
  {
    key: "7_6",
    anabat: "Mnat",
    name: "Natterers",
    count: 0,
  },
  {
    key: "7_7",
    anabat: "NSL",
    name: "Nyctalus: Leislers, Noctule",
    count: 0.8,
  },
  {
    key: "7_8",
    anabat: "Plaur",
    name: "Long eared",
    count: 0,
  },
  {
    key: "7_9",
    anabat: "Bbarb",
    name: "Long eared",
    count: 0,
  },
  {
    key: "8_0", //next
    anabat: "Rfer",
    name: "GHB",
    count: 4,
  },
  {
    key: "8_1",
    anabat: "Rhip",
    name: "LHB",
    count: 1,
  },
  {
    key: "8_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 11.75,
  },
  {
    key: "8_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 23.5,
  },
  {
    key: "8_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 0.5,
  },
  {
    key: "8_5",
    anabat: "MbraMmys",
    name: "Myotis Brandt's / Whiskered",
    count: 0,
  },
  {
    key: "8_6",
    anabat: "Mnat",
    name: "Natterers",
    count: 0.25,
  },
  {
    key: "8_7",
    anabat: "NSL",
    name: "Nyctalus: Leislers, Noctule",
    count: 1.5,
  },
  {
    key: "8_8",
    anabat: "Plaur",
    name: "Long eared",
    count: 0,
  },
  {
    key: "8_9",
    anabat: "Bbarb",
    name: "Long eared",
    count: 0,
  },
  {
    key: "9_0", //next
    anabat: "Rfer",
    name: "GHB",
    count: 1.4,
  },
  {
    key: "9_1",
    anabat: "Rhip",
    name: "LHB",
    count: 0.4,
  },
  {
    key: "9_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 23.4,
  },
  {
    key: "9_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 99.8,
  },
  {
    key: "9_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 68.8,
  },
  {
    key: "9_5",
    anabat: "MbraMmys",
    name: "Myotis Brandt's / Whiskered",
    count: 76.6,
  },
  {
    key: "9_6",
    anabat: "Mnat",
    name: "Natterers",
    count: 0.2,
  },
  {
    key: "9_7",
    anabat: "NSL",
    name: "Nyctalus: Leislers, Noctule",
    count: 2.2,
  },
  {
    key: "9_8",
    anabat: "Plaur",
    name: "Long eared",
    count: 0,
  },
  {
    key: "9_9",
    anabat: "Bbarb",
    name: "Long eared",
    count: 0,
  },
  {
    key: "10_0", //next
    anabat: "Rfer",
    name: "GHB",
    count: 1,
  },
  {
    key: "10_1",
    anabat: "Rhip",
    name: "LHB",
    count: 0,
  },
  {
    key: "10_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 0,
  },
  {
    key: "10_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 1,
  },
  {
    key: "10_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 0,
  },
  {
    key: "10_5",
    anabat: "MbraMmys",
    name: "Myotis Brandt's / Whiskered",
    count: 0,
  },
  {
    key: "10_6",
    anabat: "Mnat",
    name: "Natterers",
    count: 0,
  },
  {
    key: "10_7",
    anabat: "NSL",
    name: "Nyctalus: Leislers, Noctule",
    count: 0,
  },
  {
    key: "10_8",
    anabat: "Plaur",
    name: "Long eared",
    count: 0,
  },
  {
    key: "10_9",
    anabat: "Bbarb",
    name: "Long eared",
    count: 0,
  },
];
