var resultsList2025 = [
  {
    key: "0_0", 
    anabat: "Rfer",
    name: "Greater Horseshoe",
    count: 0, //TOTALS 
  },
  {
    key: "0_1",
    anabat: "Rhip",
    name: "LHB",
    count: 2,
  },
  {
    key: "0_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 3,
  },
  {
    key: "0_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 4, ///?
  },
  {
    key: "0_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 0,
  },
  {
    key: "0_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 2,
  },
  {
    key: "0_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 54,
  },
  {
    key: "0_7",
    anabat: "Plaur",
    name: "Long-eared",
    count: 0,
  },
  {
    key: "0_8",
    anabat: " ",
    name: "Bechsteins",
    count: 0,
  },
  {
    key: "0_9",
    anabat: "Bbarb",
    name: "Barbesterelle",
    count: 0,
  },
  {
    key: "1_0", //barton town
    anabat: "Rfer",
    name: "GHB",
    count: 22,
  },
  {
    key: "1_1",
    anabat: "Rhip",
    name: "LHB",
    count: 8,
  },
  {
    key: "1_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 626,
  },
  {
    key: "1_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 110,
  },
  {
    key: "1_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 44,
  },
  {
    key: "1_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 96,
  },
  {
    key: "1_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 42,
  },
  {
    key: "1_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 0,
  },
  {
    key: "1_8",
    anabat: " ",
    name: "Bechsteins",
    count: 0,
  },
  {
    key: "1_9",
    anabat: "Bbarb",
    name: "barbestrelle",
    count: 2,
  },
  {
    key: "2_0", //Big + Bumpston******************************//NOT READY/////
    anabat: "Rfer",
    name: "GHB",
    count: 2,
  },
  {
    key: "2_1",
    anabat: "Rhip",
    name: "LHB",
    count: 2,
  },
  {
    key: "2_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 26,
  },
  {
    key: "2_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 2,
  },
  {
    key: "2_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 0,
  },
  {
    key: "2_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 0,
  },
  {
    key: "2_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 70,
  },
  {
    key: "2_7",
    anabat: "Plaur",
    name: "Long eared",
    count: 4,
  },
  {
    key: "2_8",
    anabat: " ",
    name: "Bechsteins",
    count: 0,
  },
  {
    key: "2_9",
    anabat: "Bbarb",
    name: "Barbestrelle",
    count: 0,
  },
  {
    key: "3_0", //FIELD KITCHEN******************************////
    anabat: "Rfer",
    name: "GHB",
    count: 84,
  },
  {
    key: "3_1",
    anabat: "Rhip",
    name: "LHB",
    count: 40,
  },
  {
    key: "3_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 3204,
  },
  {
    key: "3_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 1022,
  },
  {
    key: "3_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 20,
  },
  {
    key: "3_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 106, //?
  },
  {
    key: "3_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 586,
  },
  {
    key: "3_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 0,
  },
  {
    key: "3_8",
    anabat: " ",
    name: "Bechstein's",
    count: 0,
  },
  {
    key: "3_9",
    anabat: "Bbarb",
    name: "barbestrelle",
    count: 121,
  },
  {
    key: "4_0", //**************///
    anabat: "Rfer",
    name: "GHB",
    count: 22,
  },
  {
    key: "4_1",
    anabat: "Rhip",
    name: "LHB",
    count: 14,
  },
  {
    key: "4_2",
    anabat: "Ppip",
    name: "Common Pipestrelle",
    count: 206,
  },
  {
    key: "4_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 52,
  },
  {
    key: "4_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 0,
  },
  {
    key: "4_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 14, // whiskered or Brant
  },
  {
    key: "4_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 226,
  },
  {
    key: "4_7",
    anabat: "Plaur",
    name: "Long-eared",
    count: 30,
  },
  {
    key: "4_8",
    anabat: " ",
    name: "Bechstein's",
    count: 0,
  },
  {
    key: "4_9",
    anabat: "Bbarb",
    name: "barb",
    count: 6,
  },
  {
    key: "5_0", //JOHN SMITH*********************////
    anabat: "Rfer",
    name: "GHB",
    count: 6,
  },
  {
    key: "5_1",
    anabat: "Rhip",
    name: "LHB",
    count: 10,
  },
  {
    key: "5_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 1024,
  },
  {
    key: "5_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 428,
  },
  {
    key: "5_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 2,
  },
  {
    key: "5_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 6,
  },
  {
    key: "5_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 82,
  },
  {
    key: "5_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 8,
  },
  {
    key: "5_8",
    anabat: " ",
    name: "Bechstein's",
    count: 0,
  },
  {
    key: "5_9",
    anabat: "Bbarb",
    name: "bbarb",
    count: 2,
  },
  {
    key: "6_0", //POLYTUNNELS - NOT FINISHED//***************************** */
    anabat: "Rfer",
    name: "GHB",
    count: 4,
  },
  {
    key: "6_1",
    anabat: "Rhip",
    name: "LHB",
    count: 0,
  },
  {
    key: "6_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 88,
  },
  {
    key: "6_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 96,
  },
  {
    key: "6_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 0,
  },
  {
    key: "6_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 0,
  },
  {
    key: "6_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 10,
  },
  {
    key: "6_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 0,
  },
  {
    key: "6_8",
    anabat: " ",
    name: "Bechstein's",
    count: 0,
  },
  {
    key: "6_9",
    anabat: "Bbarb",
    name: "bbarb",
    count: 0,
  },
  {
    key: "7_0", //TUCKERS FIELDS//************NOT FINISHED************* */
    anabat: "Rfer",
    name: "GHB",
    count: 94,
  },
  {
    key: "7_1",
    anabat: "Rhip",
    name: "LHB",
    count: 50,
  },
  {
    key: "7_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 510,
  },
  {
    key: "7_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 612,
  },
  {
    key: "7_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 4,
  },
  {
    key: "7_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 30,
  },
  {
    key: "7_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 18,
  },
  {
    key: "7_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 0,
  },
  {
    key: "7_8",
    anabat: " ",
    name: "Bechstein's",
    count: 2,
  },
  {
    key: "7_9",
    anabat: "Bbarb",
    name: "bbarb",
    count: 0,
  },
  {
    key: "8_0", //TWO RESERVOIRS//////************************* */
    anabat: "Rfer",
    name: "GHB",
    count: 59,
  },
  {
    key: "8_1",
    anabat: "Rhip",
    name: "LHB",
    count: 0,
  },
  {
    key: "8_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 143,
  },
  {
    key: "8_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 150,
  },
  {
    key: "8_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 0,
  },
  {
    key: "8_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 1,
  },
  {
    key: "8_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 38,
  },
  {
    key: "8_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 0,
  },
  {
    key: "8_8",
    anabat: " ",
    name: "Bechstein's",
    count: 0,
  },
  {
    key: "8_9",
    anabat: "Bbarb",
    name: "bBarb",
    count: 2,
  },
  {
    key: "9_0", //GLORIAS WOOD
    anabat: "Rfer",
    name: "GHB",
    count: 13,
  },
  {
    key: "9_1",
    anabat: "Rhip",
    name: "LHB",
    count: 1,
  },
  {
    key: "9_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 20,
  },
  {
    key: "9_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 3,
  },
  {
    key: "9_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 0,
  },
  {
    key: "9_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 0,
  },
  {
    key: "9_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 7,
  },
  {
    key: "9_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 0,
  },
  {
    key: "9_8",
    anabat: " ",
    name: "Bechstein's",
    count: 0,
  },
  {
    key: "9_9",
    anabat: "Bbarb",
    name: "bBarb",
    count: 0,
  },
  {
    key: "10_0", //BLANK//////////////////////////////
    anabat: "Rfer",
    name: "GHB",
    count: 0,
  },
  {
    key: "10_1",
    anabat: "Rhip",
    name: "LHB",
    count: 0,
  },
  {
    key: "10_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 0,
  },
  {
    key: "10_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 0,
  },
  {
    key: "10_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 0,
  },
  {
    key: "10_5",
    anabat: "MbraMmys",
    name: "Myotis Brandt's / Whiskered",
    count: 0,
  },
  {
    key: "10_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 0,
  },
  {
    key: "10_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 0,
  },
  {
    key: "10_8",
    anabat: " ",
    name: "Bechstein's",
    count: 0,
  },
  {
    key: "10_9",
    anabat: "Bbarb",
    name: "Barbastelle",
    count: 0,
  },
];
