var resultsList2025 = [
  {
    key: "0_0", 
    anabat: "Rfer",
    name: "Greater Horseshoe",
    count: 0, //TOTALS 
  },
  {
    key: "0_1",
    anabat: "Rhip",
    name: "LHB",
    count: 2,
  },
  {
    key: "0_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 1.5,
  },
  {
    key: "0_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 2, ///?
  },
  {
    key: "0_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 0,
  },
  {
    key: "0_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 2,
  },
  {
    key: "0_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 27,
  },
  {
    key: "0_7",
    anabat: "Plaur",
    name: "Long-eared",
    count: 0,
  },
  {
    key: "0_8",
    anabat: " ",
    name: "Bechsteins",
    count: 0,
  },
  {
    key: "0_9",
    anabat: "Bbarb",
    name: "Barbesterelle",
    count: 0,
  },
  {
    key: "1_0", //barton town
    anabat: "Rfer",
    name: "GHB",
    count: 7.3,
  },
  {
    key: "1_1",
    anabat: "Rhip",
    name: "LHB",
    count: 2.6,
  },
  {
    key: "1_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 156.6,
  },
  {
    key: "1_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 27.5,
  },
  {
    key: "1_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 14.6,
  },
  {
    key: "1_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 24,
  },
  {
    key: "1_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 14,
  },
  {
    key: "1_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 0,
  },
  {
    key: "1_8",
    anabat: " ",
    name: "Bechsteins",
    count: 0,
  },
  {
    key: "1_9",
    anabat: "Bbarb",
    name: "barbestrelle",
    count: 2,
  },
  {
    key: "2_0", //Big + Bumpston******************************//NOT READY/////
    anabat: "Rfer",
    name: "GHB",
    count: 2,
  },
  {
    key: "2_1",
    anabat: "Rhip",
    name: "LHB",
    count: 2,
  },
  {
    key: "2_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 8.6,
  },
  {
    key: "2_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 2,
  },
  {
    key: "2_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 0,
  },
  {
    key: "2_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 4,
  },
  {
    key: "2_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 11.6,
  },
  {
    key: "2_7",
    anabat: "Plaur",
    name: "Long eared",
    count: 2,
  },
  {
    key: "2_8",
    anabat: " ",
    name: "Bechsteins",
    count: 0,
  },
  {
    key: "2_9",
    anabat: "Bbarb",
    name: "Barbestrelle",
    count: 0,
  },
  {
    key: "3_0", //FIELD KITCHEN******************************////
    anabat: "Rfer",
    name: "GHB",
    count: 10.5,
  },
  {
    key: "3_1",
    anabat: "Rhip",
    name: "LHB",
    count: 6.6,
  },
  {
    key: "3_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 400.5,
  },
  {
    key: "3_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 127.5,
  },
  {
    key: "3_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 3.3,
  },
  {
    key: "3_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 15.14, //?
  },
  {
    key: "3_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 73.25,
  },
  {
    key: "3_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 0,
  },
  {
    key: "3_8",
    anabat: " ",
    name: "Bechstein's",
    count: 0,
  },
  {
    key: "3_9",
    anabat: "Bbarb",
    name: "barbestrelle",
    count: 3,
  },
  {
    key: "4_0", //**************///
    anabat: "Rfer",
    name: "GHB",
    count: 3.14,
  },
  {
    key: "4_1",
    anabat: "Rhip",
    name: "LHB",
    count: 7,
  },
  {
    key: "4_2",
    anabat: "Ppip",
    name: "Common Pipestrelle",
    count: 20.6,
  },
  {
    key: "4_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 7.42,
  },
  {
    key: "4_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 0,
  },
  {
    key: "4_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 3.5, // whiskered or Brant
  },
  {
    key: "4_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 25.11,
  },
  {
    key: "4_7",
    anabat: "Plaur",
    name: "Long-eared",
    count: 4.28,
  },
  {
    key: "4_8",
    anabat: " ",
    name: "Bechstein's",
    count: 0,
  },
  {
    key: "4_9",
    anabat: "Bbarb",
    name: "barb",
    count: 3,
  },
  {
    key: "5_0", //JOHN SMITH*********************////
    anabat: "Rfer",
    name: "GHB",
    count: 2,
  },
  {
    key: "5_1",
    anabat: "Rhip",
    name: "LHB",
    count: 2.5,
  },
  {
    key: "5_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 170.67,
  },
  {
    key: "5_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 71.33,
  },
  {
    key: "5_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 2,
  },
  {
    key: "5_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 2,
  },
  {
    key: "5_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 13.67,
  },
  {
    key: "5_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 2.67,
  },
  {
    key: "5_8",
    anabat: " ",
    name: "Bechstein's",
    count: 0,
  },
  {
    key: "5_9",
    anabat: "Bbarb",
    name: "bbarb",
    count: 2,
  },
  {
    key: "6_0", //POLYTUNNELS - NOT FINISHED//***************************** */
    anabat: "Rfer",
    name: "GHB",
    count: 2,
  },
  {
    key: "6_1",
    anabat: "Rhip",
    name: "LHB",
    count: 0,
  },
  {
    key: "6_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 29.3,
  },
  {
    key: "6_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 32,
  },
  {
    key: "6_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 0,
  },
  {
    key: "6_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 0,
  },
  {
    key: "6_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 3.3,
  },
  {
    key: "6_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 0,
  },
  {
    key: "6_8",
    anabat: " ",
    name: "Bechstein's",
    count: 0,
  },
  {
    key: "6_9",
    anabat: "Bbarb",
    name: "bbarb",
    count: 0,
  },
  {
    key: "7_0", //TUCKERS FIELDS//************NOT FINISHED************* */
    anabat: "Rfer",
    name: "GHB",
    count: 31.3,
  },
  {
    key: "7_1",
    anabat: "Rhip",
    name: "LHB",
    count: 25,
  },
  {
    key: "7_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 170,
  },
  {
    key: "7_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 204,
  },
  {
    key: "7_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 4,
  },
  {
    key: "7_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 10,
  },
  {
    key: "7_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 6,
  },
  {
    key: "7_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 0,
  },
  {
    key: "7_8",
    anabat: " ",
    name: "Bechstein's",
    count: 0,
  },
  {
    key: "7_9",
    anabat: "Bbarb",
    name: "bbarb",
    count: 0,
  },
  {
    key: "8_0", //TWO RESERVOIRS//////************************* */
    anabat: "Rfer",
    name: "GHB",
    count: 0,
  },
  {
    key: "8_1",
    anabat: "Rhip",
    name: "LHB",
    count: 0,
  },
  {
    key: "8_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 0,
  },
  {
    key: "8_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 0,
  },
  {
    key: "8_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 0,
  },
  {
    key: "8_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 0,
  },
  {
    key: "8_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 0,
  },
  {
    key: "8_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 0,
  },
  {
    key: "8_8",
    anabat: " ",
    name: "Bechstein's",
    count: 0,
  },
  {
    key: "8_9",
    anabat: "Bbarb",
    name: "bBarb",
    count: 0,
  },
  {
    key: "9_0", //GLORIAS WOOD
    anabat: "Rfer",
    name: "GHB",
    count: 0,
  },
  {
    key: "9_1",
    anabat: "Rhip",
    name: "LHB",
    count: 0,
  },
  {
    key: "9_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 0,
  },
  {
    key: "9_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 0,
  },
  {
    key: "9_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 0,
  },
  {
    key: "9_5",
    anabat: "MbraMmys",
    name: "Myotis Other",
    count: 0,
  },
  {
    key: "9_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 0,
  },
  {
    key: "9_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 0,
  },
  {
    key: "9_8",
    anabat: " ",
    name: "Bechstein's",
    count: 0,
  },
  {
    key: "9_9",
    anabat: "Bbarb",
    name: "bBarb",
    count: 0,
  },
  {
    key: "10_0", //BLANK//////////////////////////////
    anabat: "Rfer",
    name: "GHB",
    count: 0,
  },
  {
    key: "10_1",
    anabat: "Rhip",
    name: "LHB",
    count: 0,
  },
  {
    key: "10_2",
    name: "Common Pipestrelle",
    anabat: "Ppip",
    count: 0,
  },
  {
    key: "10_3",
    anabat: "Ppyg",
    name: "Soprano Pipestrelle",
    count: 0,
  },
  {
    key: "10_4",
    anabat: "Mdau",
    name: "Myotis Daubentons",
    count: 0,
  },
  {
    key: "10_5",
    anabat: "MbraMmys",
    name: "Myotis Brandt's / Whiskered",
    count: 0,
  },
  {
    key: "10_6",
    anabat: "NSL",
    name: "Nyctalus",
    count: 0,
  },
  {
    key: "10_7",
    anabat: "Plaur",
    name: "Long - eared",
    count: 0,
  },
  {
    key: "10_8",
    anabat: " ",
    name: "Bechstein's",
    count: 0,
  },
  {
    key: "10_9",
    anabat: "Bbarb",
    name: "Barbastelle",
    count: 0,
  },
];
